In [14]:
import numpy as np

MyList = [1,2,3,4]
MyArr = np.array(MyList)
print(type(MyArr))
print(np.arange(0,11,4))
print(np.zeros(4))
print(np.ones((5,2)))
print(np.random.randint(4,7))
print(np.random.randint(4,7,(5,3)))
np.random.seed(101)
ArrX = np.random.randint(5,11,10)
print(ArrX)
print(ArrX.max())
print(ArrX.min())
print(ArrX.mean())
print(ArrX.argmax())
print(ArrX.reshape(2,5))

<class 'numpy.ndarray'>
[0 4 8]
[0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
4
[[4 4 6]
 [5 4 5]
 [4 5 6]
 [4 5 6]
 [4 4 5]]
[ 8  6 10  8  6 10  5  9  5 10]
10
5
7.7
2
[[ 8  6 10  8  6]
 [10  5  9  5 10]]
